export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSES = "GET_COURSE";
export const COURSES_LOADING = "COURSES_LOADING";

export const COURSE_NUMBERS_LOADING ="COURSE_NUMBERS_LOADING"

export const ADD_QUERY_PARAMETERS = "ADD_QUERY_PARAMETERS";

export enum queryActionTypes {
    GET_COURSE_NUMBERS = "GET_COURSE_NUMBERS",
    SET_SELECTED_YEAR = 'SET_SELECTED_YEAR',
    SET_SELECTED_TERM = 'SET_SELECTED_TERM',
    SET_SELECTED_COURSE_NUMBER = 'SET_SELECTED_COURSE_NUMBER',
    SET_SELECTED_COURSE_CODE = 'SET_SELECTED_COURSE_CODE'
}
