export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSES = "GET_COURSE";
export const COURSES_LOADING = "COURSES_LOADING";

export const GET_COURSE_NUMBERS = "GET_COURSE_NUMBERS";
export const COURSE_NUMBERS_LOADING ="COURSE_NUMBERS_LOADING"
