export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSES = "GET_COURSE";
export const COURSES_LOADING = "COURSES_LOADING";

export const COURSE_NUMBERS_LOADING ="COURSE_NUMBERS_LOADING"


export enum queryActionTypes {
    GET_COURSE_NUMBERS = "GET_COURSE_NUMBERS",
    SEND_QUERY = "SEND_QUERY",
    SET_SELECTED_YEAR = 'SET_SELECTED_YEAR',
    SET_SELECTED_TERM = 'SET_SELECTED_TERM',
    SET_SELECTED_COURSE_NUMBER = 'SET_SELECTED_COURSE_NUMBER',
    SET_SELECTED_COURSE_CODE = 'SET_SELECTED_COURSE_CODE',
    SET_SELECTED_COURSE_CODE_SAGA = 'SET_SELECTED_COURSE_CODE_SAGA',
    ADD_QUERY_PARAMETERS_AND_REMOVE_SUBSETS = 'ADD_QUERY_PARAMETERS_AND_REMOVE_SUBSETS',
    ADD_QUERY_PARAMETERS = "ADD_QUERY_PARAMETERS"
}
